# -*- coding: utf-8 -*-
"""Feature  Selection_standardization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13u9CMLsqLuMrrRVEeead6e_mcE8Cd96F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Social_Network_Ads.csv')

df.head()

df= df.iloc[:,2:]

df.sample(5)

"""#Train Test Split"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased',axis =1),
                                                    df['Purchased'],
                                                    test_size = 0.3,
                                                    random_state =0)
X_train.shape, X_test.shape



"""#Standard Scaler

"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#fit the scaler to the train set,it will learn the parameters
scaler.fit(X_train)

#transform train and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

scaler.mean_

X_train

X_train_scaled

X_train_scaled = pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled =pd.DataFrame(X_test_scaled,columns=X_test.columns)

np.round(X_train.describe(),1)

"""#Effect of scaling

"""

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12, 5))

ax1.scatter(X_train['Age'], X_train['EstimatedSalary'])
ax1.set_title("Before Scaling")
ax2.scatter(X_train_scaled['Age'], X_train_scaled['EstimatedSalary'],color='red')
ax2.set_title("After Scaling")
plt.show()

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12, 5))

# before scaling
ax1.set_title('Before Scaling')
sns.kdeplot(X_train['Age'], ax=ax1)
sns.kdeplot(X_train['EstimatedSalary'], ax=ax1)

# after scaling
ax2.set_title('After Standard Scaling')
sns.kdeplot(X_train_scaled['Age'], ax=ax2)
sns.kdeplot(X_train_scaled['EstimatedSalary'], ax=ax2)
plt.show()



"""#Why Scaling is important"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr_scaled = LogisticRegression()

lr.fit(X_train,y_train)
lr_scaled.fit(X_test,y_test)

y_pred = lr.predict(X_test)
Y_pred_scaled = lr_scaled.predict(X_test_scaled)

from sklearn.metrics import accuracy_score

print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,Y_pred_scaled))









