# -*- coding: utf-8 -*-
"""pandas profiling_ydata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121TG22AnmfXGaLi68aPRQTVtc6HgjUiZ
"""

!pip install ydata-profiling

import pandas as pd

df = pd.read_csv('/content/train.csv')

from ydata_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file("output.html")



















